### ISSUE TITLE
Organization / repo home

### ISSUE THREAD

**Issue by bluss** [indexmap-rs/indexmap#291]
Hi @cuviper, are you interested in moving this crate's git repo? Maybe it can move to a new home since I'm not taking care of it - while you are doing so quite well.

**Comment by cuviper** [comment]
Sure! At the very least, it would be nice to have admin access so I can access branch protection and such. If we move to an org, we can also start using GH merge queues (akin to bors).

**Comment by bluss** [comment]
I'm not on my proper computer so I might be mistaken, but there could also be no admin access role for personal repositories like this one, so I can't find a way to give you that.

I would suggest we move the repo to an org, but I would also suggest we drop me as maintainer unfortunately, since I defacto do not contribute at this point.

I don't claim any ownership, by which I mean whatever you decide is fine.
(If you would ask me, maybe the rust lang org would be an ok host for this crate?)

**Comment by cuviper** [comment]
I can ask about adding it to @rust-lang, or else a new org would be fine with me.

Are you also looking to offload other crates? For example, `either` could reasonably move to @rust-itertools (which I'm not a member of) or @rayon-rs (which I am), as the 2 biggest dependents, or else @rust-lang or something new as well...

**Comment by bluss** [comment]
Yes, it would be good to move either as well

**Comment by cuviper** [comment]
I created a new org @indexmap-rs and invited you. I think you'll be able to transfer the repo as soon as you accept. I also moved the `equivalent` crate there, since I had split that from `indexmap` in the first place.

I don't feel a need to remove you as a maintainer, if only to keep up the "bus factor", but you can depart if you would really prefer to do so.

For `either`, I think we can just move it to @rayon-rs, ok? I'll invite you there as well if you agree.

**Comment by bluss** [comment]
@cuviper Right, thanks! Will move the repo now then

@jswrenn Either was sort of created as a crate offshoot from itertools, that's the history of it. But with this it would move to the rayon organization like @cuviper suggested. I hope that works :slightly_smiling_face:

**Comment by bluss** [comment]
Repos were moved, as is now evident, github should provide all redirects (including for git etc.)

- bluss/indexmap → indexmap-rs/indexmap
- bluss/either → rayon-rs/either

**Comment by bluss** [comment]
Thanks a lot for accepting the new ownership :100:

**Comment by jswrenn** [comment]
@cuviper Given either's history as an offshoot of itertools, could you keep us in the loop if y'all decide to bump either's MSRV? It's our only required dependency, and so far our policy has been to treat MSRV bumps as breaking, which is only really tenable when all of your dependencies have the same owner.

**Comment by cuviper** [comment]
@jswrenn that's no problem for me. Would you like to be a co-maintainer for `either`? Not that it's busy, but it would be nice to have a backup person, at least.

**Comment by jswrenn** [comment]
Sure! Happy to help!

**Comment by cuviper** [comment]
Thanks, I think we're set!
