### ISSUE TITLE
MutableKeys for IndexSet

### ISSUE THREAD

**Issue by Morganamilo** [indexmap-rs/indexmap#322]
Would it be possible to add a way to mutate keys in Set like you can Map?

**Comment by cuviper** [comment]
I suppose we could, but can you say more about your use-case for this?

Also, you can approximate this by using `IndexMap<T, ()>` with `MutableKeys` instead of `IndexSet`.

**Comment by Morganamilo** [comment]
I have a struct that I'm storing in a set and only hashing the name. I then want to edit some of the fields along the life of the program.
