### ISSUE TITLE
Feature request: join two or more IndexMap

### ISSUE THREAD

**Issue by M5135213521asd3** [indexmap-rs/indexmap#336]
Hi, could it be possible to implement join two IndexMap to one, or insert one IndexMap to another?

Thank you,
Marian

**Comment by cuviper** [comment]
There's no method for it, as there are many variations of behavior that might be desired. The most generic way is to use [`Extend`](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#impl-Extend%3C(K,+V)%3E-for-IndexMap%3CK,+V,+S%3E), like `map.extend(other)`, or `map.extend(other.drain(..))` to keep the other allocation.

> This is equivalent to calling [`insert`](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.insert) for each of them in order, which means that for keys that already existed in the map, their value is updated but it keeps the existing order.

If you want different update semantics, you can iterate the other map yourself and use the [`entry`](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.entry) API for efficient lookups to update the target map.

It's also up to you to decide the desired order of the resulting map, and make that happen.

**Comment by cuviper** [comment]
The standard library also has [`BTreeMap::append`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.append), [`BTreeSet::append`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.append), and [`Vec::append`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append), but not for `HashMap` and `HashSet`. I think it would be fine to add to `IndexMap::append` and `IndexSet::append` though, with the same `insert`-replacement semantics that I mentioned before.
