### ISSUE TITLE
Request: Random access of key/value pairs

### ISSUE THREAD

**Issue by travis-leith** [indexmap-rs/indexmap#338]
Right now I can either [index keys](https://docs.rs/indexmap/latest/indexmap/map/struct.Keys.html#impl-Index%3Cusize%3E-for-Keys%3C'a,+K,+V%3E) or [index values](https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#impl-Index%3Cusize%3E-for-IndexMap%3CK,+V,+S%3E). I cannot (as far as I can tell) index (key, value) pairs.

I would like map[usize] -> (key, value).

The workaround is to convert my `IndexMap<Key, Value>` to `IndexMap<Key, (Key, Value>>` which is not ideal.

**Comment by bluss** [comment]
I think you can in fact do that, the methods for that are here (3 methods) https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html#method.get_index

**Comment by travis-leith** [comment]
No idea how I missed that. I will test it before closing. Thanks.
