### ISSUE TITLE
`replace_text` fails every time with `Could not parse ToUnicodeCMap: Error!`

### ISSUE THREAD

**Issue by axoking** [indexmap-rs/indexmap#351]
The `replace_text` function of the `Document` struct is not working.

Example code:

```rust
use lopdf::Document;

fn main() {
	let mut doc = Document::load("document.pdf").unwrap();

	if let Err(error) = doc.replace_text(1, "Hello World", "Goodbye world") {
		println!("{error}");
	}

	doc.save("modified.pdf").unwrap();
}
```

Gives the following output:

```
ToUnicode CMap error: Could not parse ToUnicodeCMap: Error!
```

Happens even with a simple PDF document created by libre office (see below):
[document.pdf](https://github.com/user-attachments/files/17116050/document.pdf)
[document.odt](https://github.com/user-attachments/files/17116058/Untitled.1.odt)

**Comment by cuviper** [comment]
This is not directly using `indexmap` -- perhaps you meant to file an issue on `lopdf`?
https://github.com/J-F-Liu/lopdf

**Comment by cuviper** [comment]
Feel free to re-open if `lopdf` investigation comes back to a bug in `indexmap`.

**Comment by axoking** [comment]
Bruh, misclicked. Was meant for lopdf, I'm sorry!
