### ISSUE TITLE
Can't add colon-space twice.

### ISSUE THREAD

**Issue by amab8901** [indexmap-rs/indexmap#359]
# How to reproduce:

``` rust
use indexmap::IndexMap;

fn main() {
    let mut test_hashmap: IndexMap<String, bool> =
        IndexMap::from_iter(vec![(": ".to_string(), false)]);

    dbg!(&test_hashmap);

    test_hashmap.insert(": ".to_string(), false);

    dbg!(&test_hashmap);
}
```

# Expected:
Hashmap with two entries:
1) `": ": false`
2) `": ": false`

# Received:
Hashmap with one entry:
1) `": ": false`

**Comment by cuviper** [comment]
This is not a multi-map, so it should be expected that only one entry exists for a given key. The `insert` docs say:

> If an equivalent key already exists in the map: the key remains and retains in its place in the order, its corresponding value is updated with `value`, and the older value is returned inside `Some(_)`.

That's the same behavior as `std::collections::HashMap` as well. What led you to expect otherwise?

**Comment by amab8901** [comment]
> This is not a multi-map, so it should be expected that only one entry exists for a given key. The `insert` docs say:
> 
> > If an equivalent key already exists in the map: the key remains and retains in its place in the order, its corresponding value is updated with `value`, and the older value is returned inside `Some(_)`.
> 
> That's the same behavior as `std::collections::HashMap` as well. What led you to expect otherwise?

because in a Hashmap, the only way to retrieve entries is by their keys. But in Indexmap you also have an order (i.e. 5th item, 10th item, etc). So that way, if you have the same key repeated multiple times, you could still distinguish them by their index
