### ISSUE TITLE
An insert_sorted() method

### ISSUE THREAD

**Issue by Schmeckinger** [indexmap-rs/indexmap#89]
I would like to use ```IndexMap``` as a ```BTreeMap``` with faster reads and slower writes.
But calling ```sort_keys()``` after every ```insert()``` is pretty slow.
Would it be possible to have a ```insert_sorted()``` method that would just insert the element before the next bigger one?

**Comment by garro95** [comment]
Apart from the question, I think you should call `sort_keys` in a lazy way just before the lookup and not after each insertion. But this may depend on the specific case.

**Comment by bluss** [comment]
`insert_sorted` is still *O(n)* so I'm not sure it's good enough.

**Comment by ArtemGr** [comment]
[binary_search_by](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.binary_search_by): "*If the value is not found then Result::Err is returned, containing the index where a matching element could be inserted while maintaining sorted order*".

Implementing positional insert ( https://github.com/bluss/indexmap/pull/83 ) and access should be enough to maintain a sort order.

**Comment by cuviper** [comment]
Binary search is O(log n), but inserting at an arbitrary index is still O(n), both for the internal `Vec::insert` and for all the index updates in the raw hash table.

**Comment by ArtemGr** [comment]
Replacing `Vec` with [Vector](https://docs.rs/imbl/1.0.1/imbl/struct.Vector.html) will make it `O(log n)`, and then we'll have a map with two indices. Wouldn't that be something?  😆
